"""Generate a synthetic cohort, train the conformal panel, fit the planner.

EVERY sample here is generated by phenora/physics.py. None of it is
measured. Separability in this cohort is a property of the generative
model and says nothing about real-world accuracy - it validates the
software architecture, not the assay.
"""
import json
import time
import numpy as np

from phenora.pipeline import (CLASSES, FEATURES, make_cartridge, run_cartridge,
                              ConformalPanel, EIGPlanner)

N_PER_CLASS = 80
BAD_CONTACT_RATE = 0.08
SEED = 20260902


def main():
    rng = np.random.default_rng(SEED)
    X, y, Q, meta = [], [], [], []
    t0 = time.time()
    for ci, lab in enumerate(CLASSES):
        for k in range(N_PER_CLASS):
            bad = rng.random() < BAD_CONTACT_RATE
            cart = make_cartridge(lab, rng, force_bad_contact=bad)
            x, feats, qc, _ = run_cartridge(cart, rng)
            X.append(x); y.append(lab); Q.append(qc['score'])
            meta.append(dict(label=lab, qc=qc['verdict'], trust=qc['score'],
                             flags=qc['flags'], forced_bad=bad))
        print(f"  {lab:<14s} {N_PER_CLASS} cartridges  ({time.time()-t0:6.1f}s)")
    X = np.array(X); y = np.array(y); Q = np.array(Q)

    idx = rng.permutation(len(y))
    n = len(y); a, b = int(0.6 * n), int(0.8 * n)
    tr, cal, te = idx[:a], idx[a:b], idx[b:]

    panel = ConformalPanel(alpha=0.10, seed=1).fit(X[tr], y[tr], X[cal], y[cal])
    planner = EIGPlanner(CLASSES).fit(X[tr], y[tr])

    sets, probs = panel.predict_set(X[te])
    top1 = np.array([panel.classes_[i] for i in probs.argmax(1)])
    cover = np.mean([y[te][i] in sets[i] for i in range(len(te))])
    size = np.mean([len(s) for s in sets])
    acc = float(np.mean(top1 == y[te]))

    print(f"\n  held-out n={len(te)}")
    print(f"  top-1 accuracy (synthetic cohort) : {acc:.3f}")
    print(f"  conformal empirical coverage      : {cover:.3f}   (target 0.900)")
    print(f"  mean prediction-set size          : {size:.2f}")
    print(f"  qhat                              : {panel.qhat:.4f}")

    from sklearn.metrics import confusion_matrix
    cm = confusion_matrix(y[te], top1, labels=CLASSES)
    print("\n  confusion (rows=truth):")
    print("      " + " ".join(f"{c[:6]:>7s}" for c in CLASSES))
    for c, row in zip(CLASSES, cm):
        print(f"  {c[:12]:<12s}" + " ".join(f"{v:>7d}" for v in row))

    np.savez('cohort.npz', X=X, y=y, Q=Q, tr=tr, cal=cal, te=te)
    import pickle
    with open('models.pkl', 'wb') as fh:
        pickle.dump(dict(panel=panel, planner=planner), fh)
    with open('cohort_report.json', 'w') as fh:
        json.dump(dict(n=int(n), features=FEATURES, classes=CLASSES,
                       accuracy=acc, coverage=float(cover),
                       mean_set_size=float(size), qhat=panel.qhat,
                       qc_reject=int(sum(m['qc'] == 'REJECT' for m in meta)),
                       qc_review=int(sum(m['qc'] == 'REVIEW' for m in meta)),
                       runtime_s=time.time() - t0), fh, indent=2)
    print(f"\n  QC: {sum(m['qc']=='REJECT' for m in meta)} rejected, "
          f"{sum(m['qc']=='REVIEW' for m in meta)} flagged for review, "
          f"{sum(m['forced_bad'] for m in meta)} injected bad contacts")
    print(f"  total {time.time()-t0:.1f}s")


if __name__ == '__main__':
    main()
