"use client";

import { useState, useEffect } from "react";
import SimulationScene from "@/components/simulation/SimulationScene";
import { Play, Pause, RotateCcw, Cpu, ShieldAlert, Award } from "lucide-react";

interface TrajectoryPoint {
  time: number;
  temperature: number;
  phi_control: number;
  phi_test: number;
  F_control: number;
  F_test: number;
  delta_F: number;
  fpga_decision: string;
  fpga_state_color: string;
  frequency_sweep: {
    frequencies: number[];
    control_magnitude: number[];
    control_phase: number[];
    test_magnitude: number[];
    test_phase: number[];
  };
}

interface Dataset {
  metadata: any;
  trajectory: TrajectoryPoint[];
}

export default function SimulationLab() {
  // Load data state
  const [data, setData] = useState<{ susceptible: Dataset; resistant: Dataset } | null>(null);
  const [treatmentType, setTreatmentType] = useState<"susceptible" | "resistant">("susceptible");
  
  // Parameter Sliders
  const [conductivity, setConductivity] = useState(1.0); // S/m
  const [cellConcentration, setCellConcentration] = useState(0.02); // 0.0 to 1.0 fraction
  const [temperature, setTemperature] = useState(37.0); // °C
  const [Rs, setRs] = useState(120.0); // Ohms
  const [Rct, setRct] = useState(4000.0); // Ohms
  const [Cdl, setCdl] = useState(5.0); // uF
  
  // Playback control
  const [currentTimeIndex, setCurrentTimeIndex] = useState(0);
  const [isPlaying, setIsPlaying] = useState(false);

  // Load JSON dataset generated by Python
  useEffect(() => {
    fetch("/datasets/simulation_data.json")
      .then((res) => res.json())
      .then((json) => {
        setData(json);
      })
      .catch((err) => console.error("Error loading simulation dataset:", err));
  }, []);

  // Time playback logic
  useEffect(() => {
    let interval: any;
    if (isPlaying && data) {
      interval = setInterval(() => {
        setCurrentTimeIndex((prev) => {
          if (prev >= data[treatmentType].trajectory.length - 1) {
            setIsPlaying(false);
            return prev;
          }
          return prev + 1;
        });
      }, 300);
    }
    return () => clearInterval(interval);
  }, [isPlaying, data, treatmentType]);

  if (!data) {
    return (
      <div className="bg-[#0A192F] min-h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-10 w-10 border-b-2 border-[#17B169] mx-auto mb-4"></div>
          <p className="text-gray-400 text-xs font-semibold tracking-wider">LOADING SCIENTIFIC MODEL DATA...</p>
        </div>
      </div>
    );
  }

  const activeDataset = data[treatmentType];
  const trajectory = activeDataset.trajectory;
  const currentPoint = trajectory[currentTimeIndex];

  // Dynamically calculate Z(f) magnitude and phase for equivalent circuit frequency curves on client-side
  const frequencies = [100, 200, 500, 1000, 2000, 5000, 10000, 20000, 50000, 100000];
  const complexSweep = frequencies.map((f) => {
    // Randles equivalent circuit: Z(f) = Rs + Rct / (1 + j * 2 * pi * f * Rct * Cdl)
    const omega = 2 * Math.PI * f;
    const Cdl_farad = Cdl * 1e-6;
    
    // Real and Imaginary denominator: Denom = 1 + j * (omega * Rct * Cdl)
    const denomReal = 1.0;
    const denomImag = omega * Rct * Cdl_farad;
    const denomMagSq = denomReal * denomReal + denomImag * denomImag;
    
    // Rct / (denomReal + j*denomImag) = Rct * (denomReal - j*denomImag) / denomMagSq
    const zIntReal = (Rct * denomReal) / denomMagSq;
    const zIntImag = (-Rct * denomImag) / denomMagSq;
    
    const zReal = Rs + zIntReal;
    const zImag = zIntImag;
    
    const magnitude = Math.sqrt(zReal * zReal + zImag * zImag);
    const phase = (Math.atan2(zImag, zReal) * 180) / Math.PI;
    
    return { frequency: f, magnitude, phase };
  });

  // SVG Chart scaling helpers
  const maxDeltaF = Math.max(...trajectory.map(p => Math.abs(p.delta_F)), 1);
  const maxF = Math.max(...trajectory.map(p => Math.max(p.F_control, p.F_test)), 1);

  return (
    <div className="bg-[#0A192F] min-h-screen py-10">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Header */}
        <div className="flex flex-col md:flex-row md:items-center justify-between mb-8 pb-6 border-b border-gray-900 gap-4">
          <div>
            <div className="flex items-center space-x-3">
              <span className="text-[10px] text-[#17B169] font-extrabold tracking-widest uppercase block">SPECTRAE</span>
              <span className="bg-[#17B169]/15 text-[#17B169] border border-[#17B169]/30 text-[9px] px-2.5 py-0.5 rounded font-mono font-bold tracking-widest uppercase">MODEL STATUS: READY</span>
            </div>
            <h1 className="text-3xl font-extrabold text-white mt-1">Computational Impedance Lab</h1>
            <p className="text-gray-400 text-xs mt-1">
              Explore how electrical, biological and environmental parameters influence a simulated impedance trajectory.
            </p>
          </div>
          
          <div className="flex items-center space-x-3 bg-red-950/20 px-4 py-2.5 rounded border border-red-900/50 max-w-md">
            <ShieldAlert className="h-5 w-5 text-red-500 flex-shrink-0" />
            <span className="text-[10px] text-red-200/80 leading-normal font-medium">
              <strong>Model Disclaimer:</strong> Computational approximation for calibration. Not biological or clinical susceptibility validation.
            </span>
          </div>
        </div>

        {/* 3D Scene + Parameter Controls Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mb-8">
          
          {/* Left: 3D Visualization */}
          <div className="lg:col-span-2 h-[400px] bg-[#081526] border border-gray-800 rounded-xl overflow-hidden shadow-2xl relative">
            <SimulationScene
              cellConcentration={cellConcentration}
              conductivity={conductivity}
              temperature={temperature}
            />
          </div>

          {/* Right: Sliders */}
          <div className="bg-[#081324] border border-gray-800 rounded-xl p-6 shadow-2xl flex flex-col justify-between">
            <div>
              <span className="text-[10px] text-gray-500 font-bold tracking-widest uppercase block mb-3">Model Parameters</span>
              
              <div className="space-y-4 text-xs">
                {/* Medium Conductivity */}
                <div>
                  <div className="flex justify-between mb-1">
                    <span className="text-gray-300 font-medium">Medium Conductivity</span>
                    <span className="text-[#17B169] font-mono">{conductivity.toFixed(2)} S/m</span>
                  </div>
                  <input
                    type="range"
                    min="0.5"
                    max="2.0"
                    step="0.05"
                    value={conductivity}
                    onChange={(e) => setConductivity(parseFloat(e.target.value))}
                    className="w-full accent-[#17B169]"
                  />
                  <span className="text-[9px] text-gray-500 block mt-0.5">LITERATURE-DERIVED • Broth base electrical conductivity</span>
                </div>

                {/* Cell Concentration */}
                <div>
                  <div className="flex justify-between mb-1">
                    <span className="text-gray-300 font-medium">Cell Concentration (Inclusions)</span>
                    <span className="text-[#17B169] font-mono">{(cellConcentration * 100).toFixed(0)}%</span>
                  </div>
                  <input
                    type="range"
                    min="0.0"
                    max="1.0"
                    step="0.05"
                    value={cellConcentration}
                    onChange={(e) => setCellConcentration(parseFloat(e.target.value))}
                    className="w-full accent-[#17B169]"
                  />
                  <span className="text-[9px] text-gray-500 block mt-0.5">SYNTHETIC • Cell density loading in specimen space</span>
                </div>

                {/* Temperature */}
                <div>
                  <div className="flex justify-between mb-1">
                    <span className="text-gray-300 font-medium">Specimen Temperature</span>
                    <span className="text-[#17B169] font-mono">{temperature.toFixed(1)} °C</span>
                  </div>
                  <input
                    type="range"
                    min="20"
                    max="45"
                    step="0.5"
                    value={temperature}
                    onChange={(e) => setTemperature(parseFloat(e.target.value))}
                    className="w-full accent-[#17B169]"
                  />
                  <span className="text-[9px] text-gray-500 block mt-0.5">LITERATURE-DERIVED • Common-mode incubator temperature</span>
                </div>

                {/* Rs / Rct / Cdl block */}
                <div className="grid grid-cols-3 gap-2 pt-2 border-t border-gray-800/80">
                  <div>
                    <label className="text-gray-400 text-[10px] block">Rs (Ω)</label>
                    <input
                      type="number"
                      value={Rs}
                      onChange={(e) => setRs(Math.max(1, parseFloat(e.target.value) || 0))}
                      className="bg-[#0A192F] border border-gray-800 rounded p-1 w-full text-white font-mono text-[10px]"
                    />
                  </div>
                  <div>
                    <label className="text-gray-400 text-[10px] block">Rct (Ω)</label>
                    <input
                      type="number"
                      value={Rct}
                      onChange={(e) => setRct(Math.max(1, parseFloat(e.target.value) || 0))}
                      className="bg-[#0A192F] border border-gray-800 rounded p-1 w-full text-white font-mono text-[10px]"
                    />
                  </div>
                  <div>
                    <label className="text-gray-400 text-[10px] block">Cdl (µF)</label>
                    <input
                      type="number"
                      value={Cdl}
                      onChange={(e) => setCdl(Math.max(0.1, parseFloat(e.target.value) || 0))}
                      className="bg-[#0A192F] border border-gray-800 rounded p-1 w-full text-white font-mono text-[10px]"
                    />
                  </div>
                </div>
                <span className="text-[9px] text-gray-500 block mt-0.5">FITTED EQUIVALENT CIRCUIT • Randles cell parameters</span>

              </div>
            </div>

            <div className="pt-4 border-t border-gray-800">
              <div className="grid grid-cols-3 gap-2">
                <button
                  onClick={() => {
                    if (currentTimeIndex >= trajectory.length - 1) {
                      setCurrentTimeIndex(0);
                    }
                    setIsPlaying(true);
                  }}
                  className="text-center py-2 bg-[#17B169] hover:bg-[#139457] text-[#0A192F] rounded text-[10px] font-extrabold tracking-wider uppercase transition-all"
                >
                  Run
                </button>
                <button
                  onClick={() => setIsPlaying(false)}
                  className="text-center py-2 border border-gray-700 hover:border-gray-600 hover:bg-gray-800/40 text-gray-300 rounded text-[10px] font-extrabold tracking-wider uppercase transition-all"
                >
                  Pause
                </button>
                <button
                  onClick={() => {
                    setIsPlaying(false);
                    setCurrentTimeIndex(0);
                    setConductivity(1.0);
                    setCellConcentration(0.02);
                    setTemperature(37.0);
                    setRs(120.0);
                    setRct(4000.0);
                    setCdl(5.0);
                  }}
                  className="text-center py-2 border border-gray-700 hover:border-gray-600 hover:bg-gray-800/40 text-gray-400 hover:text-white rounded text-[10px] font-extrabold tracking-wider uppercase transition-all"
                >
                  Reset
                </button>
              </div>
            </div>

          </div>
        </div>

        {/* Playback scrubbing controls */}
        <section className="bg-[#081324] border border-gray-800 rounded-xl p-6 mb-8 shadow-xl">
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
            
            {/* Play/Pause Buttons */}
            <div className="flex items-center space-x-3">
              <button
                onClick={() => setIsPlaying(!isPlaying)}
                className="bg-[#17B169] text-[#0A192F] hover:bg-[#139457] p-3 rounded-full transition-all"
              >
                {isPlaying ? <Pause className="h-4 w-4 fill-current" /> : <Play className="h-4 w-4 fill-current" />}
              </button>
              <button
                onClick={() => {
                  setIsPlaying(false);
                  setCurrentTimeIndex(0);
                }}
                className="border border-gray-800 hover:border-gray-700 hover:bg-gray-800/40 p-3 rounded-full text-gray-300 transition-all"
              >
                <RotateCcw className="h-4 w-4" />
              </button>
              
              <div>
                <span className="text-white text-xs font-bold block uppercase tracking-wider">Scrub Susceptibility Timeline</span>
                <span className="text-[10px] text-gray-400">Current elapsed time: <strong className="text-[#17B169] font-mono">{currentPoint.time.toFixed(2)}h</strong></span>
              </div>
            </div>

            {/* Slider */}
            <div className="flex-grow flex items-center space-x-3">
              <input
                type="range"
                min="0"
                max={trajectory.length - 1}
                value={currentTimeIndex}
                onChange={(e) => {
                  setIsPlaying(false);
                  setCurrentTimeIndex(parseInt(e.target.value));
                }}
                className="w-full accent-[#17B169]"
              />
            </div>

            {/* Toggle susceptible / resistant */}
            <div className="flex bg-[#0A192F] border border-gray-800 p-1 rounded-lg">
              <button
                onClick={() => {
                  setIsPlaying(false);
                  setTreatmentType("susceptible");
                  setCurrentTimeIndex(0);
                }}
                className={`px-3 py-1.5 rounded text-[10px] font-bold tracking-widest uppercase transition-all ${
                  treatmentType === "susceptible"
                    ? "bg-red-500 text-white"
                    : "text-gray-400 hover:text-white"
                }`}
              >
                Susceptible
              </button>
              <button
                onClick={() => {
                  setIsPlaying(false);
                  setTreatmentType("resistant");
                  setCurrentTimeIndex(0);
                }}
                className={`px-3 py-1.5 rounded text-[10px] font-bold tracking-widest uppercase transition-all ${
                  treatmentType === "resistant"
                    ? "bg-[#17B169] text-[#0A192F]"
                    : "text-gray-400 hover:text-white"
                }`}
              >
                Resistant
              </button>
            </div>

          </div>
        </section>

        {/* Double charts: live impedance vs frequency + control/test/delta features vs time */}
        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8 mb-8">
          
          {/* Chart 1: Equivalent Circuit Sweep */}
          <div className="bg-[#081324] border border-gray-800 rounded-xl p-6 shadow-xl">
            <span className="text-[10px] text-[#17B169] font-bold tracking-widest uppercase block mb-1">Equivalent Circuit Sweep</span>
            <h3 className="text-white text-base font-bold mb-4">Impedance Magnitude |Z| vs. Frequency</h3>
            
            {/* Custom SVG Line Chart */}
            <div className="w-full h-64 relative bg-[#0A192F]/60 rounded-lg p-2 border border-gray-800/80">
              <svg viewBox="0 0 500 240" className="w-full h-full">
                {/* Grid Lines */}
                <line x1="40" y1="20" x2="40" y2="200" stroke="#1f2937" strokeWidth="1" />
                <line x1="40" y1="200" x2="480" y2="200" stroke="#1f2937" strokeWidth="1" />
                
                {/* Horizontal grid subdivisions */}
                <line x1="40" y1="80" x2="480" y2="80" stroke="#111827" strokeWidth="0.5" strokeDasharray="3,3" />
                <line x1="40" y1="140" x2="480" y2="140" stroke="#111827" strokeWidth="0.5" strokeDasharray="3,3" />
                
                {/* Plot the line */}
                <path
                  d={complexSweep.reduce((acc, point, idx) => {
                    const x = 40 + (idx / (complexSweep.length - 1)) * 440;
                    // Max |Z| around Rs+Rct = 10000. Normalize y to height 180.
                    const y = 200 - (point.magnitude / 10000) * 170;
                    return acc + `${idx === 0 ? "M" : "L"} ${x} ${y}`;
                  }, "")}
                  fill="none"
                  stroke="#17B169"
                  strokeWidth="2"
                />

                {/* Plot labels */}
                <text x="35" y="215" fill="#6b7280" fontSize="8" textAnchor="middle">100Hz</text>
                <text x="260" y="215" fill="#6b7280" fontSize="8" textAnchor="middle">5kHz</text>
                <text x="475" y="215" fill="#6b7280" fontSize="8" textAnchor="middle">100kHz</text>
                
                <text x="35" y="200" fill="#6b7280" fontSize="8" textAnchor="end">0 Ω</text>
                <text x="35" y="110" fill="#6b7280" fontSize="8" textAnchor="end">5k Ω</text>
                <text x="35" y="30" fill="#6b7280" fontSize="8" textAnchor="end">10k Ω</text>
              </svg>
            </div>
            <span className="text-[9px] text-gray-500 block mt-2 text-center">Live computation mapping Randles equation $Z(f)$ across sweep frequencies.</span>
          </div>

          {/* Chart 2: Biological Trajectory over time */}
          <div className="bg-[#081324] border border-gray-800 rounded-xl p-6 shadow-xl">
            <span className="text-[10px] text-[#17B169] font-bold tracking-widest uppercase block mb-1">Time Series Trajectory</span>
            <h3 className="text-white text-base font-bold mb-4">Dual Well Impedance & Delta Over Time</h3>
            
            {/* Custom SVG Line Chart */}
            <div className="w-full h-64 relative bg-[#0A192F]/60 rounded-lg p-2 border border-gray-800/80">
              <svg viewBox="0 0 500 240" className="w-full h-full">
                {/* Grid Lines */}
                <line x1="40" y1="20" x2="40" y2="200" stroke="#1f2937" strokeWidth="1" />
                <line x1="40" y1="200" x2="480" y2="200" stroke="#1f2937" strokeWidth="1" />
                
                {/* Horizontal grid subdivisions */}
                <line x1="40" y1="80" x2="480" y2="80" stroke="#111827" strokeWidth="0.5" strokeDasharray="3,3" />
                <line x1="40" y1="140" x2="480" y2="140" stroke="#111827" strokeWidth="0.5" strokeDasharray="3,3" />

                {/* Draw Control (blue line) and Test (red line) curves up to current point index */}
                <path
                  d={trajectory.slice(0, currentTimeIndex + 1).reduce((acc, point, idx) => {
                    const x = 40 + (idx / (trajectory.length - 1)) * 440;
                    const y = 200 - (point.F_control / maxF) * 170;
                    return acc + `${idx === 0 ? "M" : "L"} ${x} ${y}`;
                  }, "")}
                  fill="none"
                  stroke="#3b82f6"
                  strokeWidth="2"
                />
                
                <path
                  d={trajectory.slice(0, currentTimeIndex + 1).reduce((acc, point, idx) => {
                    const x = 40 + (idx / (trajectory.length - 1)) * 440;
                    const y = 200 - (point.F_test / maxF) * 170;
                    return acc + `${idx === 0 ? "M" : "L"} ${x} ${y}`;
                  }, "")}
                  fill="none"
                  stroke="#ef4444"
                  strokeWidth="2"
                />

                {/* Draw Delta_F (green line) */}
                <path
                  d={trajectory.slice(0, currentTimeIndex + 1).reduce((acc, point, idx) => {
                    const x = 40 + (idx / (trajectory.length - 1)) * 440;
                    // Offset and scale Delta_F
                    const y = 200 - (Math.abs(point.delta_F) / maxDeltaF) * 120;
                    return acc + `${idx === 0 ? "M" : "L"} ${x} ${y}`;
                  }, "")}
                  fill="none"
                  stroke="#17B169"
                  strokeWidth="2"
                  strokeDasharray="2,2"
                />

                {/* Scrub position line indicator */}
                {currentTimeIndex > 0 && (
                  <line
                    x1={40 + (currentTimeIndex / (trajectory.length - 1)) * 440}
                    y1="20"
                    x2={40 + (currentTimeIndex / (trajectory.length - 1)) * 440}
                    y2="200"
                    stroke="#17B169"
                    strokeWidth="1.5"
                    opacity="0.6"
                  />
                )}

                {/* Plot labels */}
                <text x="40" y="215" fill="#6b7280" fontSize="8" textAnchor="middle">0h</text>
                <text x="260" y="215" fill="#6b7280" fontSize="8" textAnchor="middle">5h</text>
                <text x="480" y="215" fill="#6b7280" fontSize="8" textAnchor="middle">10h</text>
              </svg>
              
              {/* Legend overlay */}
              <div className="absolute top-2 right-2 flex items-center space-x-4 bg-[#0A192F]/90 p-2 rounded border border-gray-800 text-[9px] font-bold">
                <div className="flex items-center space-x-1">
                  <span className="w-2.5 h-0.5 bg-[#3b82f6] inline-block"></span>
                  <span className="text-blue-400">Control F(t)</span>
                </div>
                <div className="flex items-center space-x-1">
                  <span className="w-2.5 h-0.5 bg-[#ef4444] inline-block"></span>
                  <span className="text-red-400">Test F(t)</span>
                </div>
                <div className="flex items-center space-x-1">
                  <span className="w-2.5 h-0.5 border-t border-dashed border-[#17B169] inline-block"></span>
                  <span className="text-[#17B169]">Delta ΔF(t)</span>
                </div>
              </div>
            </div>
            <span className="text-[9px] text-gray-500 block mt-2 text-center">Plotting {"$F_{control}(t)$"}, {"$F_{test}(t)$"} (1 kHz magnitude) and {"$\\Delta F(t) = F_{test} - F_{control}$"}.</span>
          </div>

        </div>

        {/* FPGA decision panel */}
        <section className="bg-[#081324] border border-gray-800 rounded-xl p-8 shadow-xl flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="flex items-start space-x-4">
            <div className="bg-[#17B169]/10 p-3 rounded-lg border border-[#17B169]/20">
              <Cpu className="h-8 w-8 text-[#17B169]" />
            </div>
            <div>
              <span className="text-[10px] text-gray-500 font-bold uppercase tracking-wider block">Decision Module</span>
              <h3 className="text-white text-lg font-bold mb-1">FPGA Real-time Halting Status</h3>
              <p className="text-gray-400 text-xs leading-relaxed max-w-xl">
                The decision status transitions dynamically as the differential impedance slope settles. Susceptibility is determined by final stable difference magnitude.
              </p>
            </div>
          </div>

          <div className="flex flex-col items-center justify-center p-6 bg-[#0A192F]/80 rounded-xl border border-gray-800 min-w-[250px] shadow-inner text-center">
            <span className="text-[9px] text-gray-500 font-bold uppercase tracking-widest block mb-2">FPGA Decision State</span>
            <div className={`px-6 py-2.5 rounded font-mono font-extrabold text-base tracking-widest mb-3 ${
              currentPoint.fpga_decision === "MEASURING"
                ? "bg-blue-900/35 border border-blue-700/50 text-blue-400"
                : currentPoint.fpga_decision === "STABLE"
                ? "bg-yellow-900/35 border border-yellow-700/50 text-yellow-500 animate-pulse"
                : "bg-green-900/35 border border-green-700/50 text-[#17B169]"
            }`}>
              {currentPoint.fpga_decision}
            </div>
            <div className="text-[10px] font-medium text-gray-400">
              {currentPoint.fpga_decision === "MEASURING" && "Stabilizing baseline and accumulating differential data points..."}
              {currentPoint.fpga_decision === "STABLE" && "Delta slope is stabilizing within threshold..."}
              {currentPoint.fpga_decision === "STOP" && (
                treatmentType === "susceptible" 
                  ? "Stable Differential Signal: Modeled electrical divergence settled." 
                  : "Stable Differential Signal: Test trajectory matches control."
              )}
            </div>
          </div>
        </section>

        {/* PHENORA Validation Ladder */}
        <section className="bg-[#081324] border border-gray-800 rounded-xl p-8 shadow-xl mt-8">
          <div className="mb-6">
            <span className="text-[10px] text-[#17B169] font-extrabold tracking-widest uppercase block">Scientific Rigor</span>
            <h3 className="text-white text-xl font-bold mt-1">PHENORA Verification & Validation Ladder</h3>
            <p className="text-gray-400 text-xs mt-1">
              Clear scientific boundaries separating verified physical equations and FEM solutions from hardware acquisitions and unvalidated clinical claims.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
            
            <div className="bg-[#0A192F] p-4 rounded-lg border border-green-900/60 relative">
              <span className="text-[9px] text-[#17B169] font-bold tracking-widest uppercase block">LEVEL 0 • Analytical</span>
              <h4 className="text-white text-xs font-bold mt-1">Conduction Equation</h4>
              <p className="text-gray-400 text-[11px] mt-1">Analytical resistance R = L / (σA) verified.</p>
              <span className="inline-block mt-3 px-2 py-0.5 rounded bg-green-950 text-[#17B169] text-[9px] font-bold">VERIFIED (100%)</span>
            </div>

            <div className="bg-[#0A192F] p-4 rounded-lg border border-green-900/60 relative">
              <span className="text-[9px] text-[#17B169] font-bold tracking-widest uppercase block">LEVEL 1 • FEM Engine</span>
              <h4 className="text-white text-xs font-bold mt-1">Elmer StatCurrent</h4>
              <p className="text-gray-400 text-[11px] mt-1">FEM solution converged (0.0000% error).</p>
              <span className="inline-block mt-3 px-2 py-0.5 rounded bg-green-950 text-[#17B169] text-[9px] font-bold">VERIFIED (100%)</span>
            </div>

            <div className="bg-[#0A192F] p-4 rounded-lg border border-blue-900/60 relative">
              <span className="text-[9px] text-blue-400 font-bold tracking-widest uppercase block">LEVEL 2 • Heterogeneous</span>
              <h4 className="text-white text-xs font-bold mt-1">Differential Sample</h4>
              <p className="text-gray-400 text-[11px] mt-1">Control vs Test Delta R computed via Elmer.</p>
              <span className="inline-block mt-3 px-2 py-0.5 rounded bg-blue-950 text-blue-400 text-[9px] font-bold">COMPUTATIONAL DEMO</span>
            </div>

            <div className="bg-[#0A192F] p-4 rounded-lg border border-blue-900/60 relative">
              <span className="text-[9px] text-blue-400 font-bold tracking-widest uppercase block">LEVEL 3 • Adaptive FPGA</span>
              <h4 className="text-white text-xs font-bold mt-1">Slope State Machine</h4>
              <p className="text-gray-400 text-[11px] mt-1">Golden reference FSM unit tested against vectors.</p>
              <span className="inline-block mt-3 px-2 py-0.5 rounded bg-blue-950 text-blue-400 text-[9px] font-bold">COMPUTATIONAL DEMO</span>
            </div>

            <div className="bg-[#0A192F] p-4 rounded-lg border border-yellow-900/60 relative">
              <span className="text-[9px] text-yellow-500 font-bold tracking-widest uppercase block">LEVEL 4 • Hardware</span>
              <h4 className="text-white text-xs font-bold mt-1">AD5933 + Heltec</h4>
              <p className="text-gray-400 text-[11px] mt-1">Known resistor calibration & UART feature stream.</p>
              <span className="inline-block mt-3 px-2 py-0.5 rounded bg-yellow-950 text-yellow-500 text-[9px] font-bold">IN PROGRESS</span>
            </div>

            <div className="bg-[#0A192F] p-4 rounded-lg border border-pink-900/60 relative">
              <span className="text-[9px] text-pink-400 font-bold tracking-widest uppercase block">LEVEL 5 • Bio Suspension</span>
              <h4 className="text-white text-xs font-bold mt-1">Electrolyte Matrix</h4>
              <p className="text-gray-400 text-[11px] mt-1">Controlled biological broth & cell load verification.</p>
              <span className="inline-block mt-3 px-2 py-0.5 rounded bg-pink-950 text-pink-400 text-[9px] font-bold">FUTURE / LAB</span>
            </div>

            <div className="bg-[#0A192F] p-4 rounded-lg border border-red-900/60 relative">
              <span className="text-[9px] text-red-400 font-bold tracking-widest uppercase block">LEVEL 6 • Clinical AST</span>
              <h4 className="text-white text-xs font-bold mt-1">Diagnostic S/I/R</h4>
              <p className="text-gray-400 text-[11px] mt-1">Patient sample clinical trial classification.</p>
              <span className="inline-block mt-3 px-2 py-0.5 rounded bg-red-950 text-red-400 text-[9px] font-bold">NOT YET VALIDATED</span>
            </div>

          </div>
        </section>

      </div>
    </div>
  );
}

