"""
PHENORA Flash - Layer 0: physical forward models.

Every impedance spectrum in this project is GENERATED by these equations.
Nothing here is measured data. The models are standard textbook forms
(Cole/Cole-Cole, Randles + CPE + Warburg, Gompertz growth, electrode
polarisation as a constant-phase element), parameterised with values that
are order-of-magnitude plausible for the stated matrix.

Purpose: give the rest of the stack (acquisition -> QC -> features ->
twin -> classifier -> planner) a physically self-consistent object to
operate on, so that the software architecture can be validated before any
hardware or clinical data exists.
"""

from dataclasses import dataclass, field
import numpy as np

E0 = 8.8541878128e-12


# ----------------------------------------------------------------------
# Generic circuit elements
# ----------------------------------------------------------------------

def z_cpe(f, Q, n):
    """Constant-phase element. Q in S*s^n, n in (0,1]."""
    w = 2 * np.pi * np.asarray(f, dtype=float)
    return 1.0 / (Q * (1j * w) ** n)


def z_warburg(f, sigma_w):
    """Semi-infinite Warburg diffusion."""
    w = 2 * np.pi * np.asarray(f, dtype=float)
    return sigma_w / np.sqrt(w) * (1 - 1j)


def z_cole(f, R0, Rinf, fc, alpha):
    """Cole impedance model - the standard descriptor for a cell suspension.

    Z = Rinf + (R0 - Rinf) / (1 + (j f/fc)^(1-alpha))
    """
    f = np.asarray(f, dtype=float)
    return Rinf + (R0 - Rinf) / (1.0 + (1j * f / fc) ** (1.0 - alpha))


def z_parallel(z1, z2):
    return (z1 * z2) / (z1 + z2)


# ----------------------------------------------------------------------
# Matrix models
# ----------------------------------------------------------------------

@dataclass
class BulkCell:
    """Bare 4-electrode conductivity/dispersion cell.

    Reports bulk ionic strength (urine specific gravity proxy) and, for
    cell-bearing fluids, the beta-dispersion arising from membrane
    polarisation. Four-electrode geometry suppresses but does not remove
    electrode polarisation, so a residual CPE is included.
    """
    k_cell: float = 120.0        # cell constant, 1/m -> ohm*S
    sigma_dc: float = 1.6        # S/m, bulk conductivity at f -> 0
    hct: float = 0.0             # volume fraction of cells (0 for urine)
    f_beta: float = 1.2e6        # beta-dispersion centre, Hz
    alpha_beta: float = 0.10     # Cole depression
    Q_ep: float = 3.0e-5         # residual electrode polarisation
    n_ep: float = 0.88

    def spectrum(self, f):
        # Maxwell-Fricke style: dispersed cells raise low-f resistivity.
        # rho_lf / rho_hf ratio grows with volume fraction.
        R_inf = self.k_cell / self.sigma_dc
        ratio = (1.0 + 0.5 * self.hct) / max(1.0 - self.hct, 1e-3) ** 1.5
        R_0 = R_inf * ratio
        z = z_cole(f, R_0, R_inf, self.f_beta, self.alpha_beta)
        return z + z_cpe(f, self.Q_ep, self.n_ep)


@dataclass
class AffinityCell:
    """Functionalised 3-electrode sensor in a redox-probe buffer.

    This is where analytical SPECIFICITY comes from. The bare spectrum is
    a Randles circuit; capture of the target analyte by the immobilised
    recognition element (antibody / aptamer / affimer) blocks electron
    transfer and inflates Rct. Coverage follows a Langmuir isotherm.
    """
    name: str = "analyte"
    Rs: float = 95.0
    Rct0: float = 480.0          # ohm, blank
    Rct_gain: float = 14.0       # max fold increase at saturation
    Kd: float = 3.0e-11          # M, dissociation constant
    Q: float = 1.4e-6
    n: float = 0.91
    sigma_w: float = 260.0
    conc: float = 0.0            # M, analyte concentration in the sample

    def coverage(self):
        return self.conc / (self.Kd + self.conc)

    def Rct(self):
        return self.Rct0 * (1.0 + self.Rct_gain * self.coverage())

    def spectrum(self, f):
        faradaic = self.Rct() + z_warburg(f, self.sigma_w)
        return self.Rs + z_parallel(faradaic, z_cpe(f, self.Q, self.n))


@dataclass
class GrowthWell:
    """Interdigitated electrode well: sample + low-conductivity medium.

    Metabolising organisms convert uncharged nutrients into charged
    metabolites, so bulk conductance rises and interfacial charge-transfer
    resistance falls as biomass accumulates. Population follows a
    modified Gompertz curve. This channel is the only one in the platform
    whose time axis carries genuine biological information, which is why
    the forecasting layer is attached here.
    """
    k_cell: float = 4.2e3
    sigma0: float = 0.12         # S/m of diluted medium
    Rct0: float = 5.2e3
    Q: float = 6.0e-7
    n: float = 0.86
    logN0: float = 4.0           # log10 CFU/mL inoculum
    A: float = 4.6               # log10 increase to plateau
    mu: float = 1.35             # log10 CFU/mL/h max growth rate
    lag: float = 1.1             # h
    beta_sigma: float = 0.62     # fractional conductance rise at plateau
    gamma_rct: float = 0.75      # fractional Rct fall at plateau
    inhibition: float = 0.0      # 0 = free growth, 1 = fully inhibited

    def logN(self, t):
        t = np.asarray(t, dtype=float)
        mu_eff = self.mu * (1.0 - self.inhibition)
        A_eff = self.A * (1.0 - self.inhibition)
        if A_eff <= 1e-6 or mu_eff <= 1e-6:
            return np.full_like(t, self.logN0)
        arg = (mu_eff * np.e / A_eff) * (self.lag - t) + 1.0
        arg = np.clip(arg, -30, 30)
        return self.logN0 + A_eff * np.exp(-np.exp(arg))

    def biomass_fraction(self, t):
        g = self.logN(t) - self.logN0
        return np.clip(g / max(self.A, 1e-6), 0.0, 1.2)

    def spectrum(self, f, t):
        b = float(np.atleast_1d(self.biomass_fraction(t))[0])
        sigma = self.sigma0 * (1.0 + self.beta_sigma * b)
        Rs = self.k_cell / sigma
        Rct = self.Rct0 * (1.0 - self.gamma_rct * b)
        return Rs + z_parallel(Rct, z_cpe(f, self.Q, self.n))


# ----------------------------------------------------------------------
# Sample = a bundle of channels
# ----------------------------------------------------------------------

@dataclass
class Sample:
    """One physical specimen presented to the cartridge."""
    matrix: str                       # 'urine' | 'blood'
    label: str                        # ground-truth class (simulation only)
    bulk: BulkCell = None
    affinity: dict = field(default_factory=dict)     # name -> AffinityCell
    growth: dict = field(default_factory=dict)       # well_id -> GrowthWell
    temperature_c: float = 36.8
    contact_quality: float = 0.95     # 0-1, drives noise and artefacts
